version: "3.8"

services:
    app:
        build: .
        container_name: safebox_app
        expose:
            - "18888"
        restart: unless-stopped

    caddy:
        image: caddy:2-alpine
        container_name: caddy_reverse_proxy
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config

volumes:
    caddy_data:
    caddy_config:
