services:
  # Rust AntTP official image
  anttp_rust:
    image: traktion/anttp:latest
    container_name: anttp_rust
    expose:
      - "8080"
    restart: unless-stopped

  # Your custom Node.js WebSocket proxy
  anttp_proxy:
    build:
      context: .
      dockerfile: Dockerfile # (place this new Dockerfile at project root)
    container_name: anttp_proxy
    environment:
      - ANTPP_ENDPOINT=http://anttp_rust:8080
    expose:
      - "8081"
    depends_on:
      - anttp_rust
    restart: unless-stopped

  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    container_name: caddy_cloudflare
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      - anttp_rust
      - anttp_proxy
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CLOUDFLARE_API_TOKEN=F2J5CmY-wYzTXBplJaeiiHcOhwSD6Y4z-tutoh5d

volumes:
  caddy_data:
  caddy_config:
